### ISSUE TITLE
New isometric map render algorithm

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare#461]
Let's move to a new isometric map rendering algorithm.
- Determine the area of tiles to draw by the screen rectangle (accounting for tile set max size+offset).
- Draw tiles at the top of the screen first, not at the y-top of the mapdata first

The algorithm is more complex but it'll be helpful in several ways.
- Efficiency, only dealing with the tiles that can possibly be visible
- We can have square oversized tiles with no extra effort
### Oversized Tiles (square)

Look at this example to see why square oversized tiles would "just work" under a new algorithm.

Compare these two common draw orders for isometric maps: http://imgur.com/NIv2a

Flare currently uses the bottom option. The algorithm I'm describing with use the top option.

Now suppose we have a tall tile that occupies a 2x2 grid area. We prefer to not slice our large images into individual grid tiles (just makes map editing etc. tedious). If we're using a good draw algorithm, we can choose to draw a square oversized tile at the right time to keep all our z-orders intact.

http://imgur.com/Ghk17

In this image, assume the numbers represent actual tall tiles. "Skipped" grid spaces have no tile.

The top example is the sophisticated algorithm. If we place our oversized tile in position #7 and draw it in that order, all of our tiles will be correctly drawn.

If we don't use that algorithm (e.g. we stick with Flare's current algorithm) we can't take this shortcut. There is no moment to draw our oversized tile that will not cause overlap issues. 

In the middle example we try drawing our oversized tile at position 8, but we might overlap any tall tile that was already drawn at position 6.

In the bottom example we might try drawing at position 6, but when tile 8 is drawn it may overlap our large tile.

See how Tiled correctly handles this situation: http://i.imgur.com/0u8zD.png -- here, the tower is a single tile but visually occupies a 5x5 grid area. Each stone slab around it is a regular single-grid-square tall tile. Everything's in the correct Z-order. Flare's current rendering code would not draw this in the correct z-order.
### Renderables

Note that we'd need to update how we sort Renderables first. So Issue #442 must be solved first.
### Example

Tiled uses this render style. https://github.com/bjorn/tiled/blob/master/src/libtiled/isometricrenderer.cpp#L158

**Comment by CelticSadness** [comment]
Problem is more complex because you dont consider tiles which are intersecting another ones.
Your solution is only valid for floors, etc... 
After 2 (hard) months of personal analisys of problem I finally found and implemented a "correct render drawing" for my new cocos2d-js game. 
Solution consists in mapping, for each tile (susceptible), which sprites are "front, back and behind". 
Once doing that you can draw them following a "recursive logic".
